spring.application.name=legacy-adapter-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/freddie-platform

server.port=8088

legacy.soap.osb.endpoint.loan-eligibility=http://localhost:8088/ws/LegacySoapService
legacy.soap.osb.endpoint.customer-verification=http://localhost:8088/ws/CustomerVerificationService
legacy.soap.osb.endpoint.loan-approval=http://localhost:8088/ws/LoanApprovalService
legacy.soap.wss.username=freddie-adapter-svc
legacy.soap.wss.password=${LEGACY_WSS_PASSWORD:secret-pass}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0

resilience4j.circuitbreaker.instances.legacy-loan-eligibility.sliding-window-size=5
resilience4j.circuitbreaker.instances.legacy-loan-eligibility.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.legacy-loan-eligibility.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.legacy-loan-eligibility.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.legacy-customer-verification.sliding-window-size=5
resilience4j.circuitbreaker.instances.legacy-customer-verification.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.legacy-customer-verification.wait-duration-in-open-state=60s

resilience4j.retry.instances.legacy-loan-eligibility.max-attempts=3
resilience4j.retry.instances.legacy-loan-eligibility.wait-duration=2s
resilience4j.retry.instances.legacy-loan-eligibility.enable-exponential-backoff=true
resilience4j.retry.instances.legacy-loan-eligibility.exponential-backoff-multiplier=2
resilience4j.retry.instances.legacy-customer-verification.max-attempts=3
resilience4j.retry.instances.legacy-customer-verification.wait-duration=2s

logging.level.com.freddieapp.legacyadapter=INFO
logging.level.org.springframework.ws=DEBUG

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

