-- =============================================================================
-- Freddie Mac-Style Home Loan Platform
-- Database  : Oracle Database 21c / 19c
-- Schema    : FREDDIE_LOANS  (loan-origination-service)
-- Script    : DML – Seed / Reference data
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = FREDDIE_LOANS;

-- =============================================================================
-- SEED: LOAN_APPLICATIONS — 5 sample mortgage applications
-- =============================================================================
INSERT INTO FREDDIE_LOANS.LOAN_APPLICATIONS (
    LOAN_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, PROPERTY_VALUE,
    PROPERTY_ADDRESS, INTEREST_RATE, LOAN_TERM_MONTHS,
    LOAN_STATUS, CREATED_BY, VERSION
) VALUES (
    SYS_GUID(), '00000000-0000-0000-0000-000000000001',
    'PURCHASE', 450000.00, 550000.00,
    '123 Maple Street, Austin, TX 78701',
    6.8500, 360, 'APPROVED', 'system', 0
);

INSERT INTO FREDDIE_LOANS.LOAN_APPLICATIONS (
    LOAN_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, PROPERTY_VALUE,
    PROPERTY_ADDRESS, INTEREST_RATE, LOAN_TERM_MONTHS,
    LOAN_STATUS, CREATED_BY, VERSION
) VALUES (
    SYS_GUID(), '00000000-0000-0000-0000-000000000002',
    'REFINANCE', 280000.00, 390000.00,
    '456 Oak Avenue, Phoenix, AZ 85001',
    6.2500, 240, 'UNDER_REVIEW', 'system', 0
);

INSERT INTO FREDDIE_LOANS.LOAN_APPLICATIONS (
    LOAN_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, PROPERTY_VALUE,
    PROPERTY_ADDRESS, INTEREST_RATE, LOAN_TERM_MONTHS,
    LOAN_STATUS, CREATED_BY, VERSION
) VALUES (
    SYS_GUID(), '00000000-0000-0000-0000-000000000003',
    'HELOC', 100000.00, 750000.00,
    '789 Pine Road, Seattle, WA 98101',
    7.1000, 120, 'SUBMITTED', 'system', 0
);

INSERT INTO FREDDIE_LOANS.LOAN_APPLICATIONS (
    LOAN_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, PROPERTY_VALUE,
    PROPERTY_ADDRESS, INTEREST_RATE, LOAN_TERM_MONTHS,
    LOAN_STATUS, REJECTED_REASON, CREATED_BY, VERSION
) VALUES (
    SYS_GUID(), '00000000-0000-0000-0000-000000000004',
    'PURCHASE', 620000.00, 700000.00,
    '321 Elm Boulevard, Chicago, IL 60601',
    7.5000, 360, 'REJECTED',
    'Credit score below minimum threshold (580 < 620)',
    'system', 0
);

INSERT INTO FREDDIE_LOANS.LOAN_APPLICATIONS (
    LOAN_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, PROPERTY_VALUE,
    PROPERTY_ADDRESS, INTEREST_RATE, LOAN_TERM_MONTHS,
    LOAN_STATUS, APPROVED_AMOUNT, DECISION_DATE, CREATED_BY, VERSION
) VALUES (
    SYS_GUID(), '00000000-0000-0000-0000-000000000005',
    'HOME_EQUITY', 200000.00, 850000.00,
    '654 Cedar Lane, Miami, FL 33101',
    6.5000, 180, 'DISBURSED',
    195000.00, SYSTIMESTAMP - INTERVAL '10' DAY,
    'system', 0
);

-- =============================================================================
-- SEED: LOAN_STATUS_HISTORY — transition trail for the APPROVED loan
-- =============================================================================
INSERT INTO FREDDIE_LOANS.LOAN_STATUS_HISTORY (
    HISTORY_ID, LOAN_ID, FROM_STATUS, TO_STATUS, CHANGED_BY, NOTES
)
SELECT
    SYS_GUID(),
    LA.LOAN_ID,
    NULL, 'PENDING',
    'system', 'Loan application created.'
FROM FREDDIE_LOANS.LOAN_APPLICATIONS LA
WHERE LA.LOAN_STATUS = 'APPROVED'
  AND ROWNUM = 1;

INSERT INTO FREDDIE_LOANS.LOAN_STATUS_HISTORY (
    HISTORY_ID, LOAN_ID, FROM_STATUS, TO_STATUS, CHANGED_BY, NOTES
)
SELECT
    SYS_GUID(),
    LA.LOAN_ID,
    'PENDING', 'SUBMITTED',
    'customer-portal', 'Customer submitted application online.'
FROM FREDDIE_LOANS.LOAN_APPLICATIONS LA
WHERE LA.LOAN_STATUS = 'APPROVED'
  AND ROWNUM = 1;

INSERT INTO FREDDIE_LOANS.LOAN_STATUS_HISTORY (
    HISTORY_ID, LOAN_ID, FROM_STATUS, TO_STATUS, CHANGED_BY, NOTES
)
SELECT
    SYS_GUID(),
    LA.LOAN_ID,
    'SUBMITTED', 'UNDER_REVIEW',
    'underwriting-service', 'Routed to underwriting queue.'
FROM FREDDIE_LOANS.LOAN_APPLICATIONS LA
WHERE LA.LOAN_STATUS = 'APPROVED'
  AND ROWNUM = 1;

INSERT INTO FREDDIE_LOANS.LOAN_STATUS_HISTORY (
    HISTORY_ID, LOAN_ID, FROM_STATUS, TO_STATUS, CHANGED_BY, NOTES
)
SELECT
    SYS_GUID(),
    LA.LOAN_ID,
    'UNDER_REVIEW', 'APPROVED',
    'underwriter-jdoe', 'DTI 32%, LTV 81.8%, Credit Score 730. Approved.'
FROM FREDDIE_LOANS.LOAN_APPLICATIONS LA
WHERE LA.LOAN_STATUS = 'APPROVED'
  AND ROWNUM = 1;

COMMIT;
