<?xml version="1.0" encoding="UTF-8"?>
<definitions name="LoanApprovalProcess"
             targetNamespace="http://xmlns.oracle.com/FreddieApp/LoanApprovalProcess"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/FreddieApp/LoanApprovalProcess"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/FreddieApp/LoanApprovalProcess" 
                    schemaLocation="LoanApprovalProcess.xsd"/>
        </schema>
    </types>

    <message name="LoanApprovalRequestMessage">
        <part name="payload" element="client:LoanApprovalRequest"/>
    </message>
    <message name="LoanApprovalResponseMessage">
        <part name="payload" element="client:LoanApprovalResponse"/>
    </message>

    <portType name="LoanApprovalProcessPortType">
        <operation name="process">
            <input message="client:LoanApprovalRequestMessage"/>
            <output message="client:LoanApprovalResponseMessage"/>
        </operation>
    </portType>

    <binding name="LoanApprovalProcessBinding" type="client:LoanApprovalProcessPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="process">
            <soap:operation soapAction="process"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>

    <service name="LoanApprovalService">
        <port name="LoanApprovalProcessPort" binding="client:LoanApprovalProcessBinding">
            <soap:address location="http://localhost:7001/soa-infra/services/default/LoanApprovalComposite/LoanApprovalService"/>
        </port>
    </service>

    <!-- Partner Link Type defines client-service relationship in BPEL -->
    <plnk:partnerLinkType name="LoanApprovalProcessPartnerLinkType">
        <plnk:role name="LoanApprovalProcessProvider" portType="client:LoanApprovalProcessPortType"/>
    </plnk:partnerLinkType>

</definitions>
