-- ============================================================
-- DB2 DDL Script for Struts Loan Portal
-- Schema: FREDDIE_LOANS
-- Run this against your IBM DB2 instance before deploying the WAR
-- ============================================================

CREATE SCHEMA FREDDIE_LOANS;

-- ============================================================
-- CUSTOMERS table
-- ============================================================
CREATE TABLE FREDDIE_LOANS.CUSTOMERS (
    CUSTOMER_ID     VARCHAR(36)     NOT NULL,
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    EMAIL           VARCHAR(200)    NOT NULL,
    PHONE_NUMBER    VARCHAR(20),
    SSN             VARCHAR(11),
    DATE_OF_BIRTH   TIMESTAMP,
    CUSTOMER_STATUS VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    ADDRESS_LINE1   VARCHAR(200),
    ADDRESS_LINE2   VARCHAR(200),
    CITY            VARCHAR(100),
    STATE           VARCHAR(2),
    ZIP_CODE        VARCHAR(10),
    CREDIT_SCORE    INTEGER,
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CHK_CUST_STATUS CHECK (CUSTOMER_STATUS IN ('ACTIVE','INACTIVE','SUSPENDED'))
);

CREATE INDEX IX_CUST_EMAIL   ON FREDDIE_LOANS.CUSTOMERS (EMAIL);
CREATE INDEX IX_CUST_STATUS  ON FREDDIE_LOANS.CUSTOMERS (CUSTOMER_STATUS);
CREATE INDEX IX_CUST_NAME    ON FREDDIE_LOANS.CUSTOMERS (LAST_NAME, FIRST_NAME);

-- ============================================================
-- LOAN_APPLICATIONS table
-- ============================================================
CREATE TABLE FREDDIE_LOANS.LOAN_APPLICATIONS (
    LOAN_ID             VARCHAR(36)     NOT NULL,
    CUSTOMER_ID         VARCHAR(36)     NOT NULL,
    LOAN_TYPE           VARCHAR(50)     NOT NULL,
    LOAN_AMOUNT         DECIMAL(18,2)   NOT NULL,
    PROPERTY_VALUE      DECIMAL(18,2),
    PROPERTY_ADDRESS    VARCHAR(500),
    INTEREST_RATE       DECIMAL(6,4),
    LOAN_TERM_MONTHS    INTEGER,
    LOAN_STATUS         VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    APPLICATION_DATE    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DECISION_DATE       TIMESTAMP,
    DISBURSEMENT_DATE   TIMESTAMP,
    APPROVED_AMOUNT     DECIMAL(18,2),
    REJECTION_REASON    VARCHAR(1000),
    CREATED_BY          VARCHAR(100),
    UPDATED_AT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VERSION             BIGINT          DEFAULT 0,
    CONSTRAINT PK_LOAN_APPS PRIMARY KEY (LOAN_ID),
    CONSTRAINT FK_LOAN_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES FREDDIE_LOANS.CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT CHK_LOAN_TYPE CHECK (LOAN_TYPE IN ('PURCHASE','REFINANCE','HELOC','HOME_EQUITY')),
    CONSTRAINT CHK_LOAN_STATUS CHECK (LOAN_STATUS IN
        ('PENDING','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','DISBURSED','CLOSED'))
);

CREATE INDEX IX_LOAN_CUSTOMER ON FREDDIE_LOANS.LOAN_APPLICATIONS (CUSTOMER_ID);
CREATE INDEX IX_LOAN_STATUS   ON FREDDIE_LOANS.LOAN_APPLICATIONS (LOAN_STATUS);
CREATE INDEX IX_LOAN_DATE     ON FREDDIE_LOANS.LOAN_APPLICATIONS (APPLICATION_DATE);
CREATE INDEX IX_LOAN_TYPE     ON FREDDIE_LOANS.LOAN_APPLICATIONS (LOAN_TYPE);

-- ============================================================
-- UNDERWRITING_DECISIONS table
-- ============================================================
CREATE TABLE FREDDIE_LOANS.UNDERWRITING_DECISIONS (
    DECISION_ID         VARCHAR(36)     NOT NULL,
    LOAN_ID             VARCHAR(36)     NOT NULL,
    UNDERWRITER_ID      VARCHAR(100),
    UNDERWRITER_NAME    VARCHAR(200),
    DECISION            VARCHAR(20)     NOT NULL,
    APPROVED_AMOUNT     DECIMAL(18,2),
    RECOMMENDED_RATE    DECIMAL(6,4),
    CONDITIONS          VARCHAR(2000),
    REJECTION_REASON    VARCHAR(2000),
    DEBT_TO_INCOME_RATIO INTEGER,
    LOAN_TO_VALUE_RATIO  INTEGER,
    CREDIT_SCORE_USED    INTEGER,
    RISK_CATEGORY       VARCHAR(10),
    NOTES               VARCHAR(4000),
    DECISION_DATE       TIMESTAMP,
    CREATED_AT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_UW_DECISIONS PRIMARY KEY (DECISION_ID),
    CONSTRAINT FK_UW_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES FREDDIE_LOANS.LOAN_APPLICATIONS (LOAN_ID),
    CONSTRAINT CHK_UW_DECISION CHECK (DECISION IN ('APPROVED','REJECTED','CONDITIONAL')),
    CONSTRAINT CHK_RISK_CAT CHECK (RISK_CATEGORY IN ('LOW','MEDIUM','HIGH'))
);

CREATE INDEX IX_UW_LOAN ON FREDDIE_LOANS.UNDERWRITING_DECISIONS (LOAN_ID);

-- ============================================================
-- AUDIT_LOG table (written by AuditInterceptor on EVERY action)
-- ============================================================
CREATE TABLE FREDDIE_LOANS.AUDIT_LOG (
    AUDIT_ID            BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY
                                        (START WITH 1 INCREMENT BY 1),
    ACTION_NAMESPACE    VARCHAR(100),
    ACTION_NAME         VARCHAR(100),
    ACTION_METHOD       VARCHAR(100),
    SESSION_USER_ID     VARCHAR(100),
    REMOTE_IP           VARCHAR(45),
    REQUEST_PARAMS      VARCHAR(2000),
    RESULT_CODE         VARCHAR(50),
    EXEC_TIME_MS        BIGINT,
    ERROR_MESSAGE       VARCHAR(500),
    AUDIT_TIMESTAMP     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);

CREATE INDEX IX_AUDIT_TS   ON FREDDIE_LOANS.AUDIT_LOG (AUDIT_TIMESTAMP DESC);
CREATE INDEX IX_AUDIT_USER ON FREDDIE_LOANS.AUDIT_LOG (SESSION_USER_ID);
CREATE INDEX IX_AUDIT_ACT  ON FREDDIE_LOANS.AUDIT_LOG (ACTION_NAME);

-- ============================================================
-- Sample seed data for development / testing
-- ============================================================
INSERT INTO FREDDIE_LOANS.CUSTOMERS VALUES
  ('c001', 'John',  'Smith',   'john.smith@email.com',  '555-100-0001', '123-45-6789', TIMESTAMP('1980-03-15-00.00.00'), 'ACTIVE',  '100 Oak St', NULL, 'Austin',  'TX', '78701', 720, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('c002', 'Sarah', 'Johnson', 'sarah.j@email.com',     '555-100-0002', '234-56-7890', TIMESTAMP('1990-07-22-00.00.00'), 'ACTIVE',  '200 Pine Ave',NULL, 'Houston', 'TX', '77001', 680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('c003', 'Mike',  'Davis',   'mike.d@email.com',      '555-100-0003', '345-67-8901', TIMESTAMP('1975-11-08-00.00.00'), 'ACTIVE',  '300 Elm Rd', NULL, 'Dallas',  'TX', '75201', 590, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('c004', 'Lisa',  'Williams','lisa.w@email.com',      '555-100-0004', '456-78-9012', TIMESTAMP('1985-05-30-00.00.00'), 'INACTIVE','400 Maple Dr',NULL, 'San Antonio','TX','78201',750, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO FREDDIE_LOANS.LOAN_APPLICATIONS
  (LOAN_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, PROPERTY_VALUE, PROPERTY_ADDRESS, LOAN_TERM_MONTHS, LOAN_STATUS, CREATED_BY)
VALUES
  ('l001', 'c001', 'PURCHASE',   450000.00, 560000.00, '100 Oak St, Austin TX 78701',  360, 'SUBMITTED',  'LOAN_OFFICER'),
  ('l002', 'c002', 'REFINANCE',  320000.00, 400000.00, '200 Pine Ave, Houston TX 77001',180, 'UNDER_REVIEW','LOAN_OFFICER'),
  ('l003', 'c001', 'HELOC',       80000.00, 560000.00, '100 Oak St, Austin TX 78701',  120, 'APPROVED',   'LOAN_OFFICER'),
  ('l004', 'c003', 'PURCHASE',   275000.00, 300000.00, '300 Elm Rd, Dallas TX 75201',  360, 'REJECTED',   'LOAN_OFFICER');

UPDATE FREDDIE_LOANS.LOAN_APPLICATIONS SET APPROVED_AMOUNT = 78000.00,   DECISION_DATE = CURRENT_TIMESTAMP WHERE LOAN_ID = 'l003';
UPDATE FREDDIE_LOANS.LOAN_APPLICATIONS SET REJECTION_REASON = 'Credit score below required threshold of 620', DECISION_DATE = CURRENT_TIMESTAMP WHERE LOAN_ID = 'l004';

-- ============================================================
-- LOAN_DOCUMENTS table
-- Stores file metadata for uploaded documents.
-- Actual file bytes live on the filesystem (managed by FileService).
--
-- Columns map directly to the LoanDocument model and DocumentDao.
-- FileOperationsService writes a parallel .meta.properties sidecar
-- file (via FileOutputStream) next to each stored file for recovery.
-- ============================================================
CREATE TABLE FREDDIE_LOANS.LOAN_DOCUMENTS (
    DOCUMENT_ID         VARCHAR(36)     NOT NULL,
    LOAN_ID             VARCHAR(36)     NOT NULL,
    CUSTOMER_ID         VARCHAR(36),
    DOCUMENT_TYPE       VARCHAR(50)     NOT NULL,
    ORIGINAL_FILE_NAME  VARCHAR(500)    NOT NULL,
    STORED_FILE_NAME    VARCHAR(500)    NOT NULL,
    FILE_PATH           VARCHAR(2000)   NOT NULL,
    FILE_SIZE_BYTES     BIGINT          NOT NULL DEFAULT 0,
    MIME_TYPE           VARCHAR(200),
    UPLOADED_BY         VARCHAR(100),
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'PENDING_REVIEW',
    REVIEW_NOTES        VARCHAR(1000),
    UPLOADED_AT         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REVIEWED_AT         TIMESTAMP,
    CONSTRAINT PK_LOAN_DOCS    PRIMARY KEY (DOCUMENT_ID),
    CONSTRAINT FK_DOC_LOAN     FOREIGN KEY (LOAN_ID)
        REFERENCES FREDDIE_LOANS.LOAN_APPLICATIONS (LOAN_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_DOC_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES FREDDIE_LOANS.CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT CHK_DOC_TYPE    CHECK (DOCUMENT_TYPE IN (
        'PAY_STUB','TAX_RETURN','BANK_STATEMENT','APPRAISAL',
        'PURCHASE_AGREEMENT','GOVERNMENT_ID','INSURANCE_POLICY','OTHER')),
    CONSTRAINT CHK_DOC_STATUS  CHECK (STATUS IN ('PENDING_REVIEW','APPROVED','REJECTED'))
);

-- Indexes for common query patterns used by DocumentDao
CREATE INDEX IX_DOC_LOAN_ID   ON FREDDIE_LOANS.LOAN_DOCUMENTS (LOAN_ID);
CREATE INDEX IX_DOC_CUSTOMER  ON FREDDIE_LOANS.LOAN_DOCUMENTS (CUSTOMER_ID);
CREATE INDEX IX_DOC_STATUS    ON FREDDIE_LOANS.LOAN_DOCUMENTS (STATUS);
CREATE INDEX IX_DOC_TYPE      ON FREDDIE_LOANS.LOAN_DOCUMENTS (DOCUMENT_TYPE);
CREATE INDEX IX_DOC_UPLOADED  ON FREDDIE_LOANS.LOAN_DOCUMENTS (UPLOADED_AT DESC);

