spring.application.name=funding-service
server.port=8091

spring.datasource.url=jdbc:h2:mem:fundingdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0

logging.level.com.freddieapp.funding=INFO
