spring.data.mongodb.uri=mongodb://freddie_admin:freddie_secret@localhost:27017/freddie_documents?authSource=admin
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
